export const signButton = 'button[data-test="sectionSign"]';
export const usernameInput = 'input[data-test="inputUsername"]';
export const passwordInput = 'input[data-test="inputPassword"]';
export const validUsername = "normal_user";
export const validPassword = "testtest2";
export const invalidCredential = "nonexistent";
export const signinButton = 'button[data-test="signinButton"]';
export const errorWrongUser = "Error: User nonexistent does not exist!";
export const errorWrongPass = "Password for user normal_user is incorrect!";
export const signinResetBttn = 'button[data-test="signinResetButton"]';
