export const signButton = 'button[data-test="sectionSign"]';
export const usernameInput = 'input[data-test="inputUsername"]';
export const passwordInput = 'input[data-test="inputPassword"]';
export const nameInput = 'input[data-test="inputName"]';
export const surnameInput = 'input[data-test="inputSurname"]';
export const emailInput = 'input[data-test="inputEmail"]';
export const retypeInput = 'input[data-test="inputRetype"]';
export const aboutInput = 'input[data-test="inputAbout"]';
export const validUsername = "normal_user";
export const validPassword = "testtest2";
export const invalidCredential = "nonexistent";
export const signinButton = 'button[data-test="signinButton"]';
export const errorWrongUser = "Error: User nonexistent does not exist!";
export const errorNonmatchPassword = "Error: Passwords do not match!";
export const errorWrongPass = "Password for user normal_user is incorrect!";
export const signinResetBttn = 'button[data-test="signinResetButton"]';
export const signoutButton = 'button[data-test="signoutButton"]';
export const signupRedirect = 'p[data-test="signupForm"]';
export const signinRedirect = 'p[data-test="singinForm"]';
export const resetPassRedirect = 'p[data-test="resetPassForm"]';
export const buttonSignup = 'button[data-type="signupButton"]';
